declare const styles: {
  readonly container: string;
  readonly header: string;
  readonly title: string;
  readonly sub: string;
  readonly totals: string;
  readonly total: string;
  readonly totalDanger: string;
  readonly totalLabel: string;
  readonly totalValue: string;
  readonly svg: string;
  readonly lineArticles: string;
  readonly lineErrors: string;
  readonly legend: string;
  readonly legendItem: string;
  readonly legendPeak: string;
  readonly swatch: string;
  readonly swatchArticles: string;
  readonly swatchErrors: string;
  readonly empty: string;
  readonly emptySub: string;
};
export = styles;
