declare const styles: {
  readonly container: string;
  readonly header: string;
  readonly title: string;
  readonly sub: string;
  readonly hero: string;
  readonly heroNum: string;
  readonly heroText: string;
  readonly heroLabel: string;
  readonly heroSub: string;
  readonly rankHead: string;
  readonly bars: string;
  readonly row: string;
  readonly name: string;
  readonly barTrack: string;
  readonly barFill: string;
  readonly count: string;
  readonly share: string;
  readonly footnote: string;
  readonly empty: string;
  readonly emptySub: string;
};
export = styles;
