declare const styles: {
  readonly container: string;
  readonly header: string;
  readonly title: string;
  readonly sub: string;
  readonly hero: string;
  readonly heroMain: string;
  readonly heroNum: string;
  readonly heroLabel: string;
  readonly heroAside: string;
  readonly heroAsideNum: string;
  readonly heroAsideLabel: string;
  readonly rankHead: string;
  readonly ranking: string;
  readonly row: string;
  readonly name: string;
  readonly track: string;
  readonly base: string;
  readonly stem: string;
  readonly dot: string;
  readonly value: string;
  readonly empty: string;
  readonly emptySub: string;
};
export = styles;
