declare const styles: {
  readonly "brand": string;
  readonly "brand-logo": string;
  readonly "brand-title": string;
  readonly "container": string;
  readonly "explore-icon": string;
  readonly "footer": string;
  readonly "health-icon": string;
  readonly "item": string;
  readonly "logout-icon": string;
  readonly "logs-icon": string;
  readonly "overview-icon": string;
  readonly "playback-icon": string;
  readonly "queue-icon": string;
  readonly "read-icon": string;
  readonly "search-icon": string;
  readonly "selected": string;
  readonly "settings-icon": string;
  readonly "title": string;
  readonly "unstyled": string;
  readonly "watchdog-icon": string;
};
export = styles;
